version: 3.0

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8-buster-browsers-legacy"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 main-test.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build