version: 2.1
 
# Define the jobs we want to run for this project
jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
        auth:
          username: Gowri45
          password: Gowri@4045  # context / project UI env-var reference
    steps:
      - checkout
      - run: python3 main.py
  test:
    docker:
      - image: cimg/<language>:<version TAG>
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: echo "this is the test job"
 
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test